config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resource :user
  resolve('User') { [:user] }

  resources :tasks

  resources :sessions, only: %i[new create index destroy] do
    delete '', action: :destroy, as: 'logout', on: :collection
  end

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/task.rb
# frozen_string_literal: true

# Task model
# :reek:MissingSafeMethod { exclude: [complete!] }
class Task < ApplicationRecord
  include NullByteCleaner

  belongs_to :user

  default_scope -> { order(created_at: :asc) }

  scope :incomplete, -> { where(completed_at: nil) }
  scope :completed,  -> { inverse_of(:incomplete)  }

  scope :overdue, -> { where(due_on: ...Time.zone.today) }

  broadcasts_to ->(task) { task.user }

  clean_null_bytes_from :name

  def complete!
    update!(completed_at: Time.zone.now) unless completed?
  end

  def completed?
    !!completed_at
  end

  def completed=(value)
    self.completed_at = !!value ? (completed_at or Time.zone.now) : nil
  end

  def overdue?
    (due_on&.< Time.zone.today) and !completed?
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# Tasks controller
class TasksController < ApplicationController
  before_action :set_task, except: %i[index new create]

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = current_user.tasks.new
  end

  def create
    current_user.tasks.create!(task_params)
    head :created
  end

  def show; end

  def edit; end

  def update
    @task.update!(task_params)
    redirect_to @task, status: :see_other
  end

  def destroy
    @task.destroy!
    head :no_content
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :due_on, :completed)
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

# Tasks controller helpers
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= turbo_frame_tag @task do %>
  <%= form_with model: @task, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |f| %>
    <%= f.text_field :name %>
    <%= f.date_field :due_on %>

    <%= f.submit %>
  <% end %>
<% end %>

app/views/tasks/_task.html.erb
<%= turbo_frame_tag task do %>
  <div data-controller="task" data-task-id="<%= task.id %>" class="<%= token_list(:task, { overdue: task.overdue? }) %>">
    <%= check_box_tag "completed-#{dom_id(task)}", 1, task.completed?, data: { action: "change->task#completed" } %>
    <%= task.name %>
    <%= task.due_on %>
    <%= link_to "Edit", edit_task_path(task) %>
    <%= link_to "Delete", task_path(task), data: { "turbo-method": "delete" } %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<%= turbo_frame_tag "tasks" do %>
  <%= render @tasks %>
<% end %>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<%= render @task %>